apiVersion: v2
name: prometheus-opencti-exporter
description: Prometheus exporter for OpenCTI metrics
version: 0.1.0-rc2
appVersion: "0.1.0"
home: https://github.com/weisshorn-cyd/opencti_exporter
sources:
    - https://github.com/weisshorn-cyd/opencti_exporter
keywords:
    - exporter
    - metrics
    - opencti
    - prometheus
maintainers:
    - name: axelfahy
      email: axel@cyd.ch
      url: https://github.com/axelfahy
type: application
